// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-htmlmin/gulp-htmlmin.d.ts
declare module 'gulp-htmlmin' {
    import * as HTMLMinifier from 'html-minifier';

    namespace htmlmin {
    }

    function htmlmin(options?: HTMLMinifier.Options): NodeJS.ReadWriteStream;

    export = htmlmin;
}
