// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-minify-html/gulp-minify-html.d.ts
declare module 'gulp-minify-html' {
    namespace minifyHtml {
        // Options from https://github.com/Swaagie/minimize#options
        interface Options {
            // Do not remove empty attributes
            empty?: boolean;

            // Do not strip CDATA from scripts
            cdata?: boolean;

            // Do not remove comments
            comments?: boolean;

            // Do not remove conditional internet explorer comments
            conditionals?: boolean;

            // Do not remove redundant attributes
            spare?: boolean;

            // Do not remove arbitrary quotes
            quotes?: boolean;

            // Preserve one whitespace
            loose?: boolean;
        }
    }

    function minifyHtml(options?: minifyHtml.Options): NodeJS.ReadWriteStream;

    export = minifyHtml;
}
